name: CI/CD Docker Deploy

on:
  push:
    branches:
      - main  # Chạy khi có thay đổi trên nhánh main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build -t my-app .
          docker tag my-app ${{ secrets.DOCKER_USERNAME }}/my-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest

  deploy:
    needs: build  # Chạy sau khi build xong
    runs-on: ubuntu-latest
    steps:
      - name: SSH vào Server và Deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-app:latest
            docker stop my-app || true
            docker rm my-app || true
            docker run -d -p 8080:8080 --name my-app ${{ secrets.DOCKER_USERNAME }}/my-app:latest
